services:
  skladno:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skladno_app
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
