name: "✨ Предложение функции"
description: Предложить новую идею, банк для СБП или улучшение UX
labels: ["enhancement"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Описание функции
      description: Какую проблему решает это улучшение?
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Как это должно работать?
      description: Опишите предлагаемое поведение или интерфейс.
    validations:
      required: true
